// Generated by CoffeeScript 1.11.1
(function() {
  var answerInt, answerText, expressionExample1, expressionExample2, getRandomInt;

  getRandomInt = function(min, max) {
    return min + Math.floor(Math.random() * (max - min + 1));
  };

  expressionExample1 = getRandomInt(1, 100);

  expressionExample2 = 8;

  answerText = prompt(expressionExample1 + ' + ' + expressionExample2 + ' = ', '');

  answerInt = +answerText;

  answerText = alert(expressionExample1 + expressionExample2);

  if (answerInt === expressionExample) {
    alert("Правильно!");
  } else {
    alert("Не правильно!");
  }

}).call(this);
